refactoring
Tatzhiro/LineairDB-storage-engine pull request #33
Opened 2022-06-24 07:15 UTC by nikezono

* separate `ha_lineairdb.cc` to two `.cc` files to distinct static variables and override methods
* define the following private methods to make DRY.
   ```
    std::string get_current_key();
    void set_current_key(const uchar* key = nullptr);
    void set_write_buffer();
    bool is_primary_key_exists();
    bool set_fields_from_lineairdb(uchar* buf,  LineairDB::Transaction& tx);
  ```
* use `{setup,teardown}_file` keyword in test.bats to reuse mysql daemon.

2022-07-07 04:46 UTC, nikezono commented on tests/test.bats
> +setup_file() {
[TODO]
mysqld frontend may cache the return values of `SELECT` queries.
We should restart MySQL server for each testcase.

2022-07-07 04:46 UTC, Tatzhiro requested changes

2022-07-07 04:48 UTC, nikezono commented on ha_lineairdb.cc
> +  if (!success) return HA_ERR_END_OF_FILE;
nice catch!

2022-07-20 06:38 UTC, nikezono commented on tests/test.bats
> +setup_file() {
reverted.

2022-07-20 06:44 UTC, nikezono commented on ha_lineairdb.cc
> +int ha_lineairdb::set_fields_from_lineairdb(uchar* buf,
this function is renamed from `ha_lineairdb::store_read_result_in_field`

2022-07-21 13:05 UTC, Tatzhiro approved these changes
lgtm👍

2022-07-22 15:28 UTC, merged